<a href="https://colab.research.google.com/github/jalalrahmanov/Projects/blob/master/SONAR_Rock_vs_Mine_Prediction_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome SONAR Rock vs Mine Prediction Project!
### About project:

Sonar (sound navigation and ranging) is a technique based on the principle of reflection of ultrasonic sound waves. These waves propagate through water and reflect on hitting the ocean bed or any object obstructing its path.

Sonar has been widely used in submarine navigation, communication with or detection of objects on or under the water surface (like other vessels), hazard identification, etc.

There are two types of sonar technology used â€” passive (listening to the sound emitted by vessels in the ocean) and active (emitting pulses and listening for their echoes).

It is important to note that research shows the use of active sonar can cause mass strandings of marine animals.

For more detailed information, you can go to my reference for this project from medium:
https://medium.com/ai-techsystems/sonar-data-mines-vs-rocks-on-cainvas-c0a08dde895b

In [72]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [73]:
  import pandas as pd   #for reading csv files (others may be)
  import numpy as np   #for doing some necessary operations
  from sklearn.model_selection import train_test_split        #for divide data to test and train part
  from sklearn.linear_model import LogisticRegression      #for creating an object from this class. It will be called as model
  from sklearn.metrics import accuracy_score      #for evalueating model


  # /content/drive/MyDrive/Kaggle/SONAR Rock_vs_Mine_Prediction_Dataset.csv

In [74]:
sonar_data = pd.read_csv('/content/drive/MyDrive/Kaggle/SONAR Rock_vs_Mine_Prediction_Dataset.csv', header=None)   #there is no header, for that reason
sonar_data                                                                                                         #give header None

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

## Data Understanding

In [75]:
sonar_data.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [76]:
sonar_data.shape    #for general understanding, 60 columns for feature and 1 target

(208, 61)

In [77]:
sonar_data.describe().T             #not really necessary. Shows us many statistical values about our dataset

    count      mean       std     min       25%      50%       75%     max
0   208.0  0.029164  0.022991  0.0015  0.013350  0.02280  0.035550  0.1371
1   208.0  0.038437  0.032960  0.0006  0.016450  0.03080  0.047950  0.2339
2   208.0  0.043832  0.038428  0.0015  0.018950  0.03430  0.057950  0.3059
3   208.0  0.053892  0.046528  0.0058  0.024375  0.04405  0.064500  0.4264
4   208.0  0.075202  0.055552  0.0067  0.038050  0.06250  0.100275  0.4010
5   208.0  0.104570  0.059105  0.0102  0.067025  0.09215  0.134125  0.3823
6   208.0  0.121747  0.061788  0.0033  0.080900  0.10695  0.154000  0.3729
7   208.0  0.134799  0.085152  0.0055  0.080425  0.11210  0.169600  0.4590
8   208.0  0.178003  0.118387  0.0075  0.097025  0.15225  0.233425  0.6828
9   208.0  0.208259  0.134416  0.0113  0.111275  0.18240  0.268700  0.7106
10  208.0  0.236013  0.132705  0.0289  0.129250  0.22480  0.301650  0.7342
11  208.0  0.250221  0.140072  0.0236  0.133475  0.24905  0.331250  0.7060
12  208.0  0.273305  0.140962  0.0184  0.166125  0.26395  0.351250  0.7131
13  208.0  0.296568  0.164474  0.0273  0.175175  0.28110  0.386175  0.9970
14  208.0  0.320201  0.205427  0.0031  0.164625  0.28170  0.452925  1.0000
15  208.0  0.378487  0.232650  0.0162  0.196300  0.30470  0.535725  0.9988
16  208.0  0.415983  0.263677  0.0349  0.205850  0.30840  0.659425  1.0000
17  208.0  0.452318  0.261529  0.0375  0.242075  0.36830  0.679050  1.0000
18  208.0  0.504812  0.257988  0.0494  0.299075  0.43495  0.731400  1.0000
19  208.0  0.563047  0.262653  0.0656  0.350625  0.54250  0.809325  1.0000
20  208.0  0.609060  0.257818  0.0512  0.399725  0.61770  0.816975  1.0000
21  208.0  0.624275  0.255883  0.0219  0.406925  0.66490  0.831975  1.0000
22  208.0  0.646975  0.250175  0.0563  0.450225  0.69970  0.848575  1.0000
23  208.0  0.672654  0.239116  0.0239  0.540725  0.69850  0.872175  1.0000
24  208.0  0.675424  0.244926  0.0240  0.525800  0.72110  0.873725  1.0000
25  208.0  0.699866  0.237228  0.0921  0.544175  0.75450  0.893800  1.0000
26  208.0  0.702155  0.245657  0.0481  0.531900  0.74560  0.917100  1.0000
27  208.0  0.694024  0.237189  0.0284  0.534775  0.73190  0.900275  1.0000
28  208.0  0.642074  0.240250  0.0144  0.463700  0.68080  0.852125  1.0000
29  208.0  0.580928  0.220749  0.0613  0.411400  0.60715  0.735175  1.0000
30  208.0  0.504475  0.213992  0.0482  0.345550  0.49035  0.641950  0.9657
31  208.0  0.439040  0.213237  0.0404  0.281400  0.42960  0.580300  0.9306
32  208.0  0.417220  0.206513  0.0477  0.257875  0.39120  0.556125  1.0000
33  208.0  0.403233  0.231242  0.0212  0.217575  0.35105  0.596125  0.9647
34  208.0  0.392571  0.259132  0.0223  0.179375  0.31275  0.593350  1.0000
35  208.0  0.384848  0.264121  0.0080  0.154350  0.32115  0.556525  1.0000
36  208.0  0.363807  0.239912  0.0351  0.160100  0.30630  0.518900  0.9497
37  208.0  0.339657  0.212973  0.0383  0.174275  0.31270  0.440550  1.0000
38  208.0  0.325800  0.199075  0.0371  0.173975  0.28350  0.434900  0.9857
39  208.0  0.311207  0.178662  0.0117  0.186450  0.27805  0.424350  0.9297
40  208.0  0.289252  0.171111  0.0360  0.163100  0.25950  0.387525  0.8995
41  208.0  0.278293  0.168728  0.0056  0.158900  0.24510  0.384250  0.8246
42  208.0  0.246542  0.138993  0.0000  0.155200  0.22255  0.324525  0.7733
43  208.0  0.214075  0.133291  0.0000  0.126875  0.17770  0.271750  0.7762
44  208.0  0.197232  0.151628  0.0000  0.094475  0.14800  0.231550  0.7034
45  208.0  0.160631  0.133938  0.0000  0.068550  0.12135  0.200375  0.7292
46  208.0  0.122453  0.086953  0.0000  0.064250  0.10165  0.154425  0.5522
47  208.0  0.091424  0.062417  0.0000  0.045125  0.07810  0.120100  0.3339
48  208.0  0.051929  0.035954  0.0000  0.026350  0.04470  0.068525  0.1981
49  208.0  0.020424  0.013665  0.0000  0.011550  0.01790  0.025275  0.0825
50  208.0  0.016069  0.012008  0.0000  0.008425  0.01390  0.020825  0.1004
51  208.0  0.013420  0.009634  0.0008  0.007275  0.01140  0.016725  0.0709
52  208.0  0.010709  0.007060  0.0005  0.005075  0.00955  0.014900  0.0390
53  208.0  0.010941  0.007301  0.0010  0.005375  0.00930  0.014500  0.0352
54  208.0  0.009290  0.007088  0.0006  0.004150  0.00750  0.012100  0.0447
55  208.0  0.008222  0.005736  0.0004  0.004400  0.00685  0.010575  0.0394
56  208.0  0.007820  0.005785  0.0003  0.003700  0.00595  0.010425  0.0355
57  208.0  0.007949  0.006470  0.0003  0.003600  0.00580  0.010350  0.0440
58  208.0  0.007941  0.006181  0.0001  0.003675  0.00640  0.010325  0.0364
59  208.0  0.006507  0.005031  0.0006  0.003100  0.00530  0.008525  0.0439

In [79]:
sonar_data[60].value_counts()          #look at target column for check inmalance in dataset. No imbalance, everything is okay

M    111
R     97
Name: 60, dtype: int64

In [80]:
sonar_data.groupby(60).mean()         #no need but shows mean values by target. means are different that's why there is some regularity

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

In [81]:
X = sonar_data.drop(columns = [60], axis = 1).values
y = sonar_data[60].values

In [82]:
X

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [83]:
y

array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M'],
      dtype=object)

# Train and test splitting

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y, random_state=1)

In [85]:
print(X_train)
print(y_train)

[[0.0414 0.0436 0.0447 ... 0.0077 0.0246 0.0198]
 [0.0123 0.0022 0.0196 ... 0.0058 0.0047 0.0071]
 [0.0152 0.0102 0.0113 ... 0.0011 0.0034 0.0033]
 ...
 [0.0117 0.0069 0.0279 ... 0.0062 0.0026 0.0052]
 [0.115  0.1163 0.0866 ... 0.0141 0.0068 0.0086]
 [0.0187 0.0346 0.0168 ... 0.0115 0.0193 0.0157]]
['M' 'R' 'R' 'M' 'R' 'R' 'R' 'M' 'R' 'R' 'M' 'M' 'R' 'R' 'M' 'R' 'R' 'M'
 'R' 'R' 'M' 'R' 'R' 'R' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'M'
 'R' 'M' 'M' 'M' 'R' 'M' 'M' 'R' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'R' 'M' 'R'
 'M' 'M' 'R' 'M' 'R' 'M' 'R' 'R' 'M' 'R' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'R' 'R' 'R' 'R' 'M' 'R' 'R' 'R' 'M' 'R' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'R' 'R' 'M' 'M' 'R' 'R' 'R'
 'M' 'M' 'M' 'M' 'R' 'M' 'M' 'M' 'R' 'M' 'R' 'R' 'M' 'M' 'R' 'R' 'R' 'M'
 'R' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'R' 'R' 'R' 'M' 'R' 'M' 'R' 'M'
 'R' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'R' 'R' 'M' 'R' 'M' 'M' 'R' 'M' 'R' 'R'
 'M' 'R' 'R' 'M' 'R' 'M' 'R' 'M' 'R' 'M' 'R' 'M' 'R' 'R' 'M' 'M' 'M' 'R'
 'M' 'R' 'M' 'R' 'M' 'M' 'M']

In [86]:
print(X.shape, X_train.shape, X_test.shape)
print(X_train.shape[0] + X_test.shape[0])         #shows sum of row size is equal to original dataset's row size

(208, 60) (187, 60) (21, 60)
208

# Model Training - LogisticRegression - because of binary classification

In [87]:
model = LogisticRegression()               #create model object

In [88]:
model.fit(X_train, y_train)                #training of model with train data. Fitted model.

LogisticRegression()

## Predicting and Model evalueation
Accuracy on train data

In [89]:
X_train_prediction = model.predict(X_train)
X_train_prediction                                 #our predictions are ready!

array(['M', 'R', 'M', 'M', 'R', 'M', 'R', 'R', 'R', 'R', 'M', 'M', 'R',
       'R', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'R', 'M', 'M',
       'R', 'R', 'R', 'M', 'M', 'R', 'M', 'R', 'M', 'R', 'R', 'M', 'M',
       'M', 'R', 'M', 'M', 'R', 'M', 'M', 'M', 'M', 'M', 'R', 'M', 'M',
       'M', 'R', 'M', 'M', 'R', 'M', 'R', 'M', 'R', 'R', 'M', 'R', 'M',
       'M', 'R', 'M', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'R', 'R',
       'R', 'M', 'M', 'R', 'R', 'M', 'R', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'R', 'R', 'R', 'M', 'M', 'R', 'M', 'R', 'M',
       'M', 'R', 'R', 'R', 'M', 'M', 'R', 'M', 'R', 'R', 'M', 'M', 'R',
       'M', 'R', 'M', 'M', 'M', 'R', 'R', 'R', 'M', 'R', 'R', 'R', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'R', 'R', 'M', 'M', 'M', 'M', 'R',
       'M', 'R', 'M', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'R', 'M', 'R',
       'R', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'R', 'M', 'R', 'M', 'R',
       'M', 'R', 'R', 'R', 'M', 'R', 'R', 'R', 'M', 'M', 'R', 'M', 'R',
       'M', 'R', 'M', 'M', 'M'], dtype=object)

In [90]:
training_data_accuracy = accuracy_score(X_train_prediction, y_train)
training_data_accuracy                    #our model predicts target with 83% probability (based on training data)

0.8342245989304813

Accuracy on test data

In [91]:
X_test_prediction = model.predict(X_test)

In [92]:
test_data_accuracy = accuracy_score(X_test_prediction, y_test)
test_data_accuracy                             #our model say target with 76% accuracy

0.7619047619047619

# Making a predicting system

In [93]:
#take a row which you want from dataset. Check it manually

string = '0.0286	0.0453	0.0277	0.0174	0.0384	0.0990	0.1201	0.1833	0.2105	0.3039	0.2988	0.4250	0.6343	0.8198	1.0000	0.9988	0.9508	0.9025	0.7234	0.5122	0.2074	0.3985	0.5890	0.2872	0.2043	0.5782	0.5389	0.3750	0.3411	0.5067	0.5580	0.4778	0.3299	0.2198	0.1407	0.2856	0.3807	0.4158	0.4054	0.3296	0.2707	0.2650	0.0723	0.1238	0.1192	0.1089	0.0623	0.0494	0.0264	0.0081	0.0104	0.0045	0.0014	0.0038	0.0013	0.0089	0.0057	0.0027	0.0051	0.0062'

number_list = [float(item) for item in string.split('	')]
number_list

[0.0286,
 0.0453,
 0.0277,
 0.0174,
 0.0384,
 0.099,
 0.1201,
 0.1833,
 0.2105,
 0.3039,
 0.2988,
 0.425,
 0.6343,
 0.8198,
 1.0,
 0.9988,
 0.9508,
 0.9025,
 0.7234,
 0.5122,
 0.2074,
 0.3985,
 0.589,
 0.2872,
 0.2043,
 0.5782,
 0.5389,
 0.375,
 0.3411,
 0.5067,
 0.558,
 0.4778,
 0.3299,
 0.2198,
 0.1407,
 0.2856,
 0.3807,
 0.4158,
 0.4054,
 0.3296,
 0.2707,
 0.265,
 0.0723,
 0.1238,
 0.1192,
 0.1089,
 0.0623,
 0.0494,
 0.0264,
 0.0081,
 0.0104,
 0.0045,
 0.0014,
 0.0038,
 0.0013,
 0.0089,
 0.0057,
 0.0027,
 0.0051,
 0.0062]

In [94]:
input_data = (number_list)

#changing the input_data to a numpy array for fast work
input_data_as_numpy_array = np.asarray(input_data)

#we have to reshape it for giving to our model. For model this is mandatory
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

#lets make a prediction for our manual selective data
prediction = model.predict(input_data_reshaped)
print('Prediction result is', prediction[0])                         #predicted R --> Great Job! Prediction is True!

if (prediction[0] == 'R'):
  print('The object is a Rock')
else:
  print('The object is a Mine')

Prediction result is R
The object is a Rock

## Thanks!